server:
  port: 8081
  servlet:
    context-path: /cell
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3307/d3_cell?useUnicode=true&passwordCharacterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.d3.cell.entity

cell:
  client_id: cell
  client_secret: cell
  grant_type: password
  accessTokenValiditySeconds: 7200 # 有效时间
  refreshTokenValiditySeconds: 86400 # 有效时间
  oauthUrl: http://localhost:8081/cell/oauth/token


sharePath: E:/WebSite/3DData/