spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
#    active: prod

logging:
  level:
    org.springframework.web: TRACE
  config: classpath:logback-spring.xml


zdy:
  cache:
    # 大小100m
    initialCapacity: 100
    # 30天
    time: 30
    # 3000条
    maximumSize: 3000

